version: '3'

networks:
  disko:
    external: true

services:
  portainer:
    image: portainer/portainer
    networks:
      disko:
    labels:
      - "traefik.port=9000"
      - "traefik.backend=portainer"
      - "traefik.frontend.rule=Host:portainer.localhost,overview.localhost"
    volumes:
      - ./portainer/data:/data/
      - /var/run/docker.sock:/var/run/docker.sock
  reverse-proxy:
    networks:
      disko:
    image: traefik:1.7-alpine
    command: --docker
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    labels:
      - "traefik.enable=true"
      - "traefik.port=8080"
      - "traefik.backend=reverse-proxy.localhost"
      - "traefik.frontend.rule=Host:reverse-proxy.localhost,rp.localhost"
    volumes:
      - "./traefik/traefik.toml:/etc/traefik/traefik.toml"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./traefik/acme.json:/etc/traefik/acme.json"
  disko-application:
    networks: 
      disko:
    image: registry.disko.love:443/disko/base
    command: tail -f /dev/null
    labels:
      - "traefik.enable=true"
      - "traefik.port=9999"
      - "traefik.backend=base"
      - "traefik.frontend.rule=Host:base.localhost"
    volumes:
      - "./certs:/certs"

    
