version: '3'

volumes:
    dbdata:
    
services:
    ###############
    # Application #
    ###############

    # Wordpress
    wordpress:
        image: disko/base
        ports:
            - 80:80
        volumes:
            - "./themes:/var/www/html/wp-content/themes:cached"
            - "./plugins:/var/www/html/wp-content/plugins:cached"
            - "./uploads:/var/www/html/wp-content/uploads:cached"
        environment:
            WORDPRESS_DB_HOST: ${MYSQL_HOST}
            WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
            WORDPRESS_DB_USER: ${MYSQL_USER}
            WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
            WORDPRESS_TABLE_PREFIX: ${WORDPRESS_TABLE_PREFIX}

    #############
    # Databases #
    #############

    # MysSQL
    db:
        image: mysql:5.7
        restart: unless-stopped
        expose:
            - 3306
        volumes:
            - dbdata:/var/lib/mysql
            - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}


    
