version: '3'

networks:
  disko:
    external: true

services:
  reverse-proxy:
    networks:
      disko:
    image: traefik:1.7-alpine
    command: --docker --acme.email="tech@disko.fr"
    ports:
      - "80:80"
      - "443:443"
    labels:
      - "traefik.enable=true"
      - "traefik.port=8080"
      #- "traefik.protocol=https"
      - "traefik.frontend.rule=Host:losange.disko.love;PathPrefixStrip: /rp/"
    volumes:
      - "./traefik/traefik.toml:/etc/traefik/traefik.toml"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./traefik/acme.json:/etc/traefik/acme.json"
